/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Collections {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface CollectionsRecipes {
  collectionId: number;
  createdAt: Generated<Timestamp>;
  recipeId: number;
}

export interface CookedRecipes {
  createdAt: Generated<Timestamp>;
  recipeId: number;
  userId: string;
}

export interface Follows {
  createdAt: Generated<Timestamp>;
  followedId: string;
  followerId: string;
}

export interface Ingredients {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface Ratings {
  createdAt: Generated<Timestamp>;
  rating: number;
  recipeId: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Recipes {
  createdAt: Generated<Timestamp>;
  duration: number;
  id: Generated<number>;
  imageUrl: string;
  steps: string;
  title: string;
  userId: string;
}

export interface RecipesIngredients {
  ingredientId: number;
  recipeId: number;
}

export interface RecipesTools {
  recipeId: number;
  toolId: number;
}

export interface SavedRecipes {
  createdAt: Generated<Timestamp>;
  recipeId: number;
  userId: string;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Tools {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  accounts: Accounts;
  collections: Collections;
  collectionsRecipes: CollectionsRecipes;
  cookedRecipes: CookedRecipes;
  follows: Follows;
  ingredients: Ingredients;
  ratings: Ratings;
  recipes: Recipes;
  recipesIngredients: RecipesIngredients;
  recipesTools: RecipesTools;
  savedRecipes: SavedRecipes;
  sessions: Sessions;
  tools: Tools;
  users: Users;
  verifications: Verifications;
}
