export const MIN_RECIPE_TITLE_LENGTH = 2;
export const MAX_RECIPE_TITLE_LENGTH = 50;

export const MIN_DURATION = 1;
export const MAX_DURATION = 1000;

export const MIN_COLLECTION_TITLE_LENGTH = 2;
export const MAX_COLLECTION_TITLE_LENGTH = 32;

export const MIN_RECIPES_TO_GENERATE_PER_REQUEST = 2;
export const MAX_RECIPES_TO_GENERATE_PER_REQUEST = 3;
